"""Deterministic builders for branch names, commit messages, and PR text."""

from __future__ import annotations

import re
import unicodedata
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from datetime import date

_BRANCH_MAX = 100

# Characters that could cause injection or filesystem/Markdown issues.
_STRIP_RE = re.compile(r"[`\[\]()<>{}|\\/*?:\"']")
# Any run of spaces/dashes/underscores collapses to a single dash.
_SEPARATOR_RE = re.compile(r"[\s\-_]+")
# Only lowercase letters, digits, and dashes survive.
_CLEAN_RE = re.compile(r"[^a-z0-9\-]")


def _slug(text: str, max_length: int = 60) -> str:
    """Convert arbitrary text into an ASCII slug that is safe inside a git ref."""
    if not text or not text.strip():
        return "untitled"

    normalized = unicodedata.normalize("NFKD", text)
    ascii_text = normalized.encode("ascii", "ignore").decode("ascii")

    lowered = ascii_text.lower()
    stripped = _STRIP_RE.sub(" ", lowered)
    dashed = _SEPARATOR_RE.sub("-", stripped)
    clean = _CLEAN_RE.sub("", dashed)
    clean = clean.strip("-")

    if not clean:
        return "untitled"

    if len(clean) > max_length:
        truncated = clean[:max_length]
        last_dash = truncated.rfind("-")
        if last_dash > max_length // 2:
            truncated = truncated[:last_dash]

        clean = truncated.strip("-")

    return clean or "untitled"


def validate_branch_name(name: str) -> str:
    """Validate a short branch name against the relevant git ref rules.

    Deliberately local (does not invoke ``git``) so a dangerous configuration is rejected before
    the target repository is mutated.
    """
    if not name:
        raise ValueError("Branch name cannot be empty")
    if name.startswith("-"):
        raise ValueError("Branch name cannot start with '-'")
    if name.startswith("/") or name.endswith("/") or "//" in name:
        raise ValueError("Branch name contains invalid '/' separators")
    if name == "@" or ".." in name or "@{" in name:
        raise ValueError("Branch name contains a sequence git does not allow")
    if name.endswith("."):
        raise ValueError("Branch name cannot end with '.'")

    invalid_chars = {"~", "^", ":", "?", "*", "[", "\\"}
    if any(ord(char) <= 32 or ord(char) == 127 or char in invalid_chars for char in name):
        raise ValueError("Branch name contains characters git does not allow")

    for component in name.split("/"):
        if not component or component.startswith(".") or component.endswith(".lock"):
            raise ValueError("Branch name contains a component git does not allow")

    return name


def build_branch_name(prefix: str, job_id: str, meeting_date: date | None) -> str:
    """Build the work branch name ``{prefix}/{job_id}[-{meeting_date}]``, validated for git."""
    suffix = f"-{meeting_date.isoformat()}" if meeting_date is not None else ""
    available = _BRANCH_MAX - len(prefix) - 1 - len(suffix)
    if available < 1:
        raise ValueError(f"Branch prefix is too long (maximum {_BRANCH_MAX - 1})")

    job_slug = _slug(job_id, max_length=available)
    return validate_branch_name(f"{prefix}/{job_slug}{suffix}")


def build_commit_message(job_id: str, n_docs: int) -> str:
    return f"docs(meetings): publish job {job_id} ({n_docs} doc{'s' if n_docs != 1 else ''})"


def build_pr_title(job_id: str, n_docs: int) -> str:
    return f"[Seshat] Meeting documents for job {job_id} — {n_docs} doc{'s' if n_docs != 1 else ''}"


def build_pr_body(job_id: str, meeting_date: date | None, files: list[str]) -> str:
    files_md = "\n".join(f"- `{f}`" for f in files)
    parts = [
        "## Documents generated by Seshat",
        "",
        f"**Job:** `{job_id}`",
    ]
    if meeting_date is not None:
        parts.append(f"**Meeting date:** {meeting_date.isoformat()}")

    parts += [
        "",
        "### Included files",
        "",
        files_md,
        "",
        "---",
        "_Auto-generated by Seshat._",
    ]
    return "\n".join(parts)
